server:
  port: 9090

app:
  ldap:
    url: ldap://137.134.56.215:3060/dc=altyn,dc=kz
    base: cn=Users,cn=SSO
    filter: (uid={0})
    username: cn=orcladmin
    password: unix11
  jwt:
    filename: jwt.jks
    password: mySecretKey
    alias: jwt
    accessTokenValiditySeconds: 300
    refreshTokenValiditySeconds: 1800

