server:
  port: 8080

app:
  ldap:
    url: ldap://137.134.56.215:3060/dc=altyn,dc=kz
    base: cn=Users,cn=SSO
    filter: (uid={0})
    username: cn=orcladmin
    password: unix11
  jwt:
    filename: key.jks
    password: 123456
    alias: certAlias
    accessTokenValiditySeconds: 300
    refreshTokenValiditySeconds: 1800

